# Generated by Django 4.2.2 on 2023-09-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('au_service', '0003_blist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BList',
        ),
    ]
