# Generated by Django 4.2.2 on 2023-09-25 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('au_service', '0006_alter_blist_bad_user_alter_blist_good_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blist',
            name='bad_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='blist',
            name='good_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
