version: '3.7'

services:
  service_1:
    container_name: service1
    build:
      context: ..
      dockerfile: Dockerfile
    entrypoint: /app/docker/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      docker/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: my_db
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/service_1/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=037700
      - POSTGRES_DB=postgres
  service2:
    container_name: service2
    build:
      context: ..
      dockerfile: ../service2/docker/Dockerfile
    entrypoint: /app2/docker/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - 8090:8090
    env_file:
      ../service2/docker/.env
    depends_on:
      - db
  service3:
    container_name: service3
    build:
      context: ..
      dockerfile: ../service_3/docker/Dockerfile
    entrypoint: /app3/docker/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8091
    ports:
      - 8091:8091
    env_file:
      ../service_3/docker/.env
    depends_on:
      - db
  redis:
    image: 'redis:alpine'
    hostname: redis
    container_name: redis
  worker2:
    container_name: worker2
    build:
      context: ..
      dockerfile: ../service2/docker/Dockerfile
    entrypoint: /app2/docker/worker-entrypoint.sh
    env_file:
      ../service2/docker/.env
    links:
      - redis
    depends_on:
      - redis
      - service2
      - db
  worker3:
    container_name: worker3
    build:
      context: ..
      dockerfile: ../service_3/docker/Dockerfile
    entrypoint: /app3/docker/worker-entrypoint.sh
    env_file:
      ../service_3/docker/.env
    links:
      - redis
    depends_on:
      - redis
      - service3
      - db
volumes:
  postgres_data: